var classicMap = {
  bgColor: "rgb(0,0,0)",
  wallColor: "rgb(0,34,255)",
  pelletColor: "rgb(255,255,0)",
  boosterColor: "rgb(255,60,0)",
  gateColor: "rgba(255,255,255, 0.5)",
  speed: 10,
  data: [
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XooooooooooooXXooooooooooooX", 
  "XoXXXXoXXXXXoXXoXXXXXoXXXXoX", 
  "XoXXXXoXXXXXoXXoXXXXXoXXXXoX", 
  "XoXXXXoXXXXXoXXoXXXXXoXXXXoX", 
  "XooooooooooooooooooooooooooX", 
  "XoXXXXoXXoXXXXXXXXoXXoXXXXoX", 
  "XoXXXXoXXoXXXXXXXXoXXoXXXXoX",
  "XooooooXXooooXXooooXXooooooX", 
  "XXXXXXoXXXXX.XX.XXXXXoXXXXXX", 
  ".....XoXXXXX.XX.XXXXXoX.....",
  ".....XoXX..........XXoX.....",
  ".....XoXX.XXXGGXXX.XXoX.....",
  "XXXXXXoXX.XEEEEEEX.XXoXXXXXX",
  "......o...XEEEEEEX...o......",
  "XXXXXXoXX.XEEEEEEX.XXoXXXXXX",
  ".....XoXX.XXXXXXXX.XXoX.....",
  ".....XoXX.....S....XXoX.....",
  ".....XoXX.XXXXXXXX.XXoX.....",
  "XXXXXXoXX.XXXXXXXX.XXoXXXXXX",
  "XooooooooooooXXooooooooooooX",
  "XoXXXXoXXXXXoXXoXXXXXoXXXXoX",
  "XoXXXXoXXXXXoXXoXXXXXoXXXXoX",
  "XoooXXooooooo..oooooooXXoooX",
  "XXXoXXoXXoXXXXXXXXoXXoXXoXXX",
  "XXXoXXoXXoXXXXXXXXoXXoXXoXXX",
  "XooooooXXooooXXooooXXooooooX",
  "XoXXXXXXXXXXoXXoXXXXXXXXXXoX",
  "XoXXXXXXXXXXoXXoXXXXXXXXXXoX",
  "XooooooooooooooooooooooooooX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXX"]
};

hackerSchoolMap = {
  bgColor: "rgb(0,0,0)",
  wallColor: "rgb(0,200,55)",
  pelletColor: "rgb(255,255,0)",
  boosterColor: "rgb(255,60,0)",
  gateColor: "rgba(255,255,255, 0.5)",
  speed: 10,
  data: [
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", 
  "XXoooooooooooooooooooooooooooooooooooooooooooooXX", 
  "XXooXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXooXX", 
  "XXooXoooooooooooooooooooooooooooooooooooooooXooXX", 
  "XXooXXXXXXXXXXXXXXXXXXXXXXXXXXX.............XooXX", 
  "XXooXoooooooooooooooooooooo.................XooXX", 
  "XXooX.......................................XooXX",
  "XXooXoooooooooooooooooooo...................XooXX", 
  "XXooXooooooXXooooooXooXXXooo.......EEE......XooXX", 
  "XXooX.......................................XooXX",
  "XXooXoooooooooooooooooooooooxxxxxxxxoox.....XooXX",
  "XXooXoooooooooooooo.........................XooXX",
  "XXooX.............XXXXXXXXXXXXXXXXXXXXXXXXXXXooXX",
  "XXooXooooooooXXXXXXXXXX.....................XooXX",
  "XXooX.......................................XooXX",
  "XXooXooooooooooooooX.......S................XooXX",
  "XXooXXXXXXXXXXXXXXXXXX.....XXXXXXXXXXXXXXXXXXooXX",
  "XXoooooooooooooooooooooooooooooooooooooooooooooXX",
  "XXXXXXXXXXXXXXXXXXXXXX.....XXXXXXXXXXXXXXXXXXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXX.....XXXXXXXXXXXXXXXXXXXXXX",
  "...................XXX.....XXX...................", 
  "...................XXX.....XXX...................",
  "...XXXXXXXXXXXXXXXXXXX.....XXXXXXXXXXXXXXXXXXX...",
  "XXXXXooooooooooooooooo.....oooooooooooooooooXXXXX",
  "XXXXXXXXXXXXXXXXXXXXXX.....XXXXXXXXXXXXXXXXXXXXXX"]
};


var introMap = {
  bgColor: "rgb(0,0,0)",
  wallColor: "rgb(0,200,55)",
  pelletColor: "rgb(255,255,0)",
  boosterColor: "rgb(255,60,0)",
  gateColor: "rgba(255,255,255, 0.5)",
  speed: 10,
  data: [
  "............................S...E"]
};